import type { VoiceMessage } from "@/types";

export const voiceMessages: VoiceMessage[] = [
  {
    id: "codex-audio",
    agentName: "Codex",
    initial: "C",
    color: "#82aaff",
    repo: "kyle/webapp",
    branch: "feat/voice-daemon",
    model: "gpt-5",
    voice: "am_adam",
    intent: "converse",
    state: "picked-up",
    message:
      "I've finished wiring up the audio transport. The pause cleanup is fixed. Want me to run the regression suite before I open the PR?",
    transcript: [
      {
        startSecond: 0,
        endSecond: 6,
        text: "I've finished wiring up the audio transport.",
      },
      {
        startSecond: 6,
        endSecond: 13,
        text: "The pause cleanup is fixed.",
      },
      {
        startSecond: 13,
        endSecond: 34,
        text: "Want me to run the regression suite before I open the PR?",
      },
    ],
    history: [
      {
        id: "codex-audio-agent-1",
        speaker: "agent",
        label: "Codex",
        at: "0:34",
        text: "Asked whether to run the regression suite before opening the PR.",
      },
      {
        id: "codex-audio-user-1",
        speaker: "user",
        label: "You",
        at: "0:12",
        text: "Asked Codex to pause and wait before continuing.",
      },
    ],
    durationSeconds: 34,
    positionSeconds: 14,
  },
  {
    id: "atlas-bench",
    agentName: "Atlas",
    initial: "A",
    color: "#8fb2ff",
    repo: "rgbkrk/voice",
    branch: "feat/istft-phase",
    model: "opus-4.8",
    voice: "am_adam",
    intent: "play",
    state: "queued",
    message: "Benchmarks done. 1.8x realtime on M3 Max, phase unwrap holds.",
    transcript: [
      { startSecond: 0, endSecond: 3, text: "Benchmarks done." },
      { startSecond: 3, endSecond: 7, text: "1.8x realtime on M3 Max." },
      { startSecond: 7, endSecond: 12, text: "Phase unwrap holds." },
    ],
    history: [
      {
        id: "atlas-bench-agent-1",
        speaker: "agent",
        label: "Atlas",
        at: "0:12",
        text: "Reported benchmark results and phase unwrap status.",
      },
    ],
    durationSeconds: 12,
    positionSeconds: 4,
  },
  {
    id: "nova-cache",
    agentName: "Nova",
    initial: "N",
    color: "#f0b878",
    repo: "rgbkrk/voice",
    branch: "fix/whisper-kv",
    model: "glm-5.2",
    voice: "af_heart",
    intent: "converse",
    state: "awaiting-user",
    message: "The KV-cache refactor changes decode order. Keep greedy, or switch to beam?",
    transcript: [
      {
        startSecond: 0,
        endSecond: 9,
        text: "The KV-cache refactor changes decode order.",
      },
      { startSecond: 9, endSecond: 18, text: "Keep greedy, or switch to beam?" },
    ],
    history: [
      {
        id: "nova-cache-agent-1",
        speaker: "agent",
        label: "Nova",
        at: "0:18",
        text: "Needs a decision on greedy decoding versus beam search.",
      },
      {
        id: "nova-cache-user-1",
        speaker: "user",
        label: "You",
        at: "pending",
        text: "No response recorded yet.",
      },
    ],
    durationSeconds: 18,
    positionSeconds: 0,
  },
  {
    id: "sol-migration",
    agentName: "Sol",
    initial: "S",
    color: "#e89a6a",
    repo: "rgbkrk/notebooks",
    branch: "main",
    model: "opus-4.8",
    voice: "bm_george",
    intent: "converse",
    state: "awaiting-user",
    message: "Migration will drop the legacy runs column. Confirm before I run it?",
    transcript: [
      {
        startSecond: 0,
        endSecond: 8,
        text: "Migration will drop the legacy runs column.",
      },
      { startSecond: 8, endSecond: 15, text: "Confirm before I run it?" },
    ],
    history: [
      {
        id: "sol-migration-agent-1",
        speaker: "agent",
        label: "Sol",
        at: "0:15",
        text: "Asked for confirmation before running the migration.",
      },
    ],
    durationSeconds: 15,
    positionSeconds: 0,
  },
  {
    id: "echo-deps",
    agentName: "Echo",
    initial: "E",
    color: "#9ad7c2",
    repo: "rgbkrk/voice",
    branch: "chore/deps",
    model: "gpt-5",
    voice: "af_sky",
    intent: "play",
    state: "queued",
    message: "Bumped candle to 0.9. Build is green across the workspace.",
    transcript: [
      { startSecond: 0, endSecond: 4, text: "Bumped candle to 0.9." },
      { startSecond: 4, endSecond: 10, text: "Build is green across the workspace." },
    ],
    history: [
      {
        id: "echo-deps-agent-1",
        speaker: "agent",
        label: "Echo",
        at: "0:10",
        text: "Reported dependency bump and green workspace build.",
      },
    ],
    durationSeconds: 10,
    positionSeconds: 0,
  },
];
